import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const [isPalindrome, setIsPalindrome] = useState(null);
  const [factorial, setFactorial] = useState(null);

  const handleCoinFlip = () => {
    const result = Math.random() < 0.5 ? "Heads" : "Tails";

    if (result === "Heads") {
      const userInput = prompt("You got Heads! Please enter a string:");

      if (userInput !== null) {
        const isPalindrome =
          userInput === userInput.split("").reverse().join("");

        isPalindrome
          ?
          setIsPalindrome(true)
          : setIsPalindrome(false)
      }
    } else {
      const userInput = prompt("You got Tails! Please enter a numeric value:");
      if (userInput !== null) {
        const number = parseInt(userInput, 10);
        if (isNaN(number)) {
          alert("Please enter a valid numeric value.");
        } else if (number < 0) {
          setFactorial(false);
        } else {
          let factorial = 1;
          for (let i = 1; i <= number; i++) {
            factorial *= i;
          }
          setFactorial(factorial);
        }
      }
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className={styles.container}>
            <button className={styles.buttonHere} onClick={handleCoinFlip}>
              Flip a coin
            </button>
            {
              isPalindrome !== null && (
                isPalindrome ? (
                  <div className={styles.trueWrapper}>
                    <p>True! Palindrome</p>
                  </div>
                ) : (
                  <div className={styles.falseWrapper}>
                    <p>False! Not a palindrome</p>
                  </div>
                )
              )
            }
            {
              factorial !== null && (
                factorial !== false ? (
                  <div className={styles.factorialTrue}>
                    <p>The factorial is {factorial}.</p>
                  </div>
                ) : (
                  <div className={styles.factorialFalse}>
                    <p>Factorial not possible for negative numbers</p>
                  </div>
                )
              )
            }
          </div>
        </main>
      </div>
    </>
  );
}
